// <auto-generated />
using System;
using Incapacidades.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Incapacidades.Infrastructure.Migrations
{
    [DbContext(typeof(IncapacidadesDbContext))]
    partial class IncapacidadesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Incapacidades.Domain.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_el")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("creado_por");

                    b.Property<DateTime>("FechaCarga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_carga")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<Guid>("IncapacidadId")
                        .HasColumnType("char(36)")
                        .HasColumnName("incapacidad_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreOriginal")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre_original");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("url_archivo");

                    b.HasKey("Id");

                    b.HasIndex("IncapacidadId");

                    b.ToTable("documentos_incapacidad", (string)null);
                });

            modelBuilder.Entity("Incapacidades.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cargo");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correo_electronico");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_el")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("creado_por");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("documento_identidad");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ingreso")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("Incapacidades.Domain.Entities.Incapacidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_el")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("creado_por");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("diagnostico");

                    b.Property<string>("EPS")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("eps");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("empleado_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("Registrada")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaRadicacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_radicacion");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<string>("NumeroRadicacion")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("numero_radicacion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("TranscripcionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_el");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("actualizado_por");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId", "FechaInicio", "FechaFin")
                        .HasDatabaseName("idx_incapacidades_empleado_periodo");

                    b.ToTable("incapacidades", (string)null);
                });

            modelBuilder.Entity("Incapacidades.Domain.Entities.PagoEPS", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_el")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_pago");

                    b.Property<Guid>("IncapacidadId")
                        .HasColumnType("char(36)")
                        .HasColumnName("incapacidad_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Periodo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("periodo");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("referencia");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IncapacidadId");

                    b.ToTable("pagos_eps", (string)null);
                });

            modelBuilder.Entity("Incapacidades.Domain.Entities.TranscripcionEPS", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_el")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_respuesta");

                    b.Property<Guid>("IncapacidadId")
                        .HasColumnType("char(36)")
                        .HasColumnName("incapacidad_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NumeroTranscripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("numero_transcripcion");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("observaciones");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IncapacidadId")
                        .IsUnique();

                    b.ToTable("transcripciones_eps", (string)null);
                });

            modelBuilder.Entity("Incapacidades.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("Roles")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Incapacidades.Domain.Entities.Documento", b =>
                {
                    b.HasOne("Incapacidades.Domain.Entities.Incapacidad", "Incapacidad")
                        .WithMany("Documentos")
                        .HasForeignKey("IncapacidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incapacidad");
                });

            modelBuilder.Entity("Incapacidades.Domain.Entities.Incapacidad", b =>
                {
                    b.HasOne("Incapacidades.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Incapacidades")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Incapacidades.Domain.Entities.PagoEPS", b =>
                {
                    b.HasOne("Incapacidades.Domain.Entities.Incapacidad", "Incapacidad")
                        .WithMany("Pagos")
                        .HasForeignKey("IncapacidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incapacidad");
                });

            modelBuilder.Entity("Incapacidades.Domain.Entities.TranscripcionEPS", b =>
                {
                    b.HasOne("Incapacidades.Domain.Entities.Incapacidad", "Incapacidad")
                        .WithOne("Transcripcion")
                        .HasForeignKey("Incapacidades.Domain.Entities.TranscripcionEPS", "IncapacidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incapacidad");
                });

            modelBuilder.Entity("Incapacidades.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("Incapacidades");
                });

            modelBuilder.Entity("Incapacidades.Domain.Entities.Incapacidad", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Pagos");

                    b.Navigation("Transcripcion");
                });
#pragma warning restore 612, 618
        }
    }
}
