# Usa la misma imagen base que en docker-compose
FROM node:20-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

COPY package*.json ./
CMD ["npm", "install"]
CMD ["npm", "start"]