# Usa la misma imagen base que en docker-compose
FROM node:20-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de configuración de dependencias
COPY package.json ./
COPY package-lock.json ./

# Instala todas las dependencias
RUN npm install

# El código fuente se montará a través del volumen en docker-compose
# No es necesario copiarlo aquí

# Comando por defecto para cuando el contenedor inicie
CMD ["npm", "start"]